name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@84b814a54950e27ac65a62069802df099405ef77 # v0.11
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: file
        # exclude files are in .clang-format-ignore
