name: scripted-checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python-tinycss2
      run: sudo apt-get install -y python3-tinycss2
    - name: Update submodules
      run: git submodule update --init --recursive
    # verify the scripts first (with a fixed commit)
    - name: Verify scripted tests
      run: tests/scripted/verify
    # run the scripts (on the current commit)
    - name: Run check-strings
      run: tests/scripted/check-strings
    - name: Run check-namespace
      run: tests/scripted/check-namespace
